package com.magnakod;
public class Constants {
    public enum SPOTIFY_TASK_TYPE{
        SPOTIFY_ARTIST_STREAM,SPOTIFY_ARTIST_FOLLOW,
        SPOTIFY_SONG_LIKE,SPOTIFY_SONG_SAVE,
        SPOTIFY_PLAYLIST_SAVE,
        SPOTIFY_PLAYLIST_STREAM,SPOTIFY_SONG_STREAM
    }
    public enum SPOTIFY_REMOTE_OR_LOCAL{
        LOCAL_TASK,REMOTE_TASK
    }

    public static SPOTIFY_REMOTE_OR_LOCAL getTaskType(SPOTIFY_TASK_TYPE tasks){
        return switch (tasks){
            case SPOTIFY_ARTIST_STREAM -> SPOTIFY_REMOTE_OR_LOCAL.REMOTE_TASK;
            case SPOTIFY_ARTIST_FOLLOW -> SPOTIFY_REMOTE_OR_LOCAL.LOCAL_TASK;
            case SPOTIFY_SONG_LIKE -> SPOTIFY_REMOTE_OR_LOCAL.LOCAL_TASK;
            case SPOTIFY_SONG_SAVE -> SPOTIFY_REMOTE_OR_LOCAL.LOCAL_TASK;
            case SPOTIFY_PLAYLIST_SAVE -> SPOTIFY_REMOTE_OR_LOCAL.LOCAL_TASK;
            case SPOTIFY_PLAYLIST_STREAM -> SPOTIFY_REMOTE_OR_LOCAL.REMOTE_TASK;
            case SPOTIFY_SONG_STREAM -> SPOTIFY_REMOTE_OR_LOCAL.LOCAL_TASK;
        };
    }
}
